### ISSUE TITLE
Writings: item_flags2[3] and itemimprovement_writingst::anon_1

### ISSUE THREAD

**Issue by kane-t** [DFHack/df-structures#105]
Couple of things associated with quires and scrolls:

item_toolst::item_flags2[3], on a quire or scroll, is the flag that indicates if the item is has a writing improvement.  It's used by, among other things, workshops to determine if an object *might* meet the [HAS_WRITING_IMPROVEMENT] requirement.  The game also checks to see if there actually is an itemimprovement_writingst in the improvements list, but it won't even look if this flag isn't set.

itemimprovement_writingst::anon_1 is a vector of ints, which are the indices into df.global.world.written_contents.all for the things written on a quire, scroll, or codex.  Currently, anon_1 is *really* hard to access, because it apparently has the same name as a subclass variable that's just an int primitive, which is shadowing it for some reason?  So in the Lua interpreter you have to use the special syntax to access it, and gm-editor can't insert into it because it can't create int32_ts (or any other primitive, I think).

**Comment by warmist** [comment]
I heard your request: added a way to insert primitives in gm-editor.

**Comment by kane-t** [comment]
Made a pull request for this (#136), so the issue can be closed and any further discussion can go over there.
