### ISSUE TITLE
item_totemst unk_a0, unk_a2, and unk_a4 determine the totem type

### ISSUE THREAD

**Issue by kane-t** [DFHack/df-structures#106]
unk_a0 appears to be the creature ID, unk_a2 appears to be the side of the body (0 for left, 1 for right) at least for bilateral creatures, and unk_a4 is the specific body part.

unk_a0 matches the mat_index for bonecrafts made of the same animal (so, if a totem has an unk_a0 of 100, that's an albatross-bone totem, same as a mat_type of 22 and mat_index of 100 means an item is made of albatross-bone).

Since "left or right side of the body" doesn't apply to all body plans, there's probably a bit more to unk_a2 than that, but it's consistent for bilaterally-symmetrical creatures, at least.

It *appears* that mat_type and mat_index are ignored for totems.  They're set, initially, from the body part you use to make it (so, mat_index starts out the same as unk_a0), but if you edit them afterward nothing appears to change.

**Comment by lethosor** [comment]
From http://www.bay12forums.com/smf/index.php?topic=139553.msg7146488#msg7146488, unk_a2 is the caste ID.
