### ISSUE TITLE
Proposal to add new attribute to fields new added to df-structures

### ISSUE THREAD

**Issue by ragundo** [DFHack/df-structures#107]
There're a lot of comments like this one sparced over all xml files
`<int32_t** name='unk_v4201_1' init-value='-1' comment='v0.42.01'/>`

I would be very interesting if a new attibute could be added to df-structures specifically for modifications/aditions:

`<int32_t name='unk_v4201_1' init-value='-1' since='v0.42.01' comment='data related to the field'/>`

This new attribute would allow to track when this field first appeared in df-structures and free the comment attribute for information related to the field function. Also, detailed logs of new fields added to DF Structures could then be easily generated by some automatic tool

**Comment by lethosor** [comment]
Angavrilov added this attribute to a couple fields, and I've been adding it as well. I haven't converted many old comments to use `since` instead, but I'll try to as I work on 0.43.05 updates.

**Comment by ragundo** [comment]
I would like to update all the data when the files will be stable with all the 64 bit changes for 0.43.05 (and merge comments not tagged with comment="" that are spreading across the files also). 
Maybe when the next version would be just released it's a good moment

**Comment by lethosor** [comment]
This looks done to me, besides a few that were missed.
