### ISSUE TITLE
Detach this fork from angavrilov/df-structures

### ISSUE THREAD

**Issue by dscorbett** [DFHack/df-structures#145]
GitHub considers DFHack/df-structures a fork of angavrilov/df-structures. This makes it impossible to search its code using the GitHub interface. This is especially bothersome because angavrilov/df-structures is not kept up to date. [“To detach the fork and turn it into a standalone repository on GitHub, contact GitHub support.”](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) Then angavrilov/df-structures should be turned into a fork of this repository.

**Comment by lethosor** [comment]
I'm not sure if there's a way to turn the base repo into a fork (or to change the base repo). It would be possible to delete and recreate angavrilov's repo, but that would nuke the issue/PR history there (not that it's too important). @angavrilov should probably handle this, though, seeing that it's his repo.

**Comment by dscorbett** [comment]
There is no way for a GitHub user to do it without destroying history, but I think GitHub Support can do it non-destructively.

**Comment by dscorbett** [comment]
I’d be happy to send GitHub a message myself, but I imagine they’ll want a maintainer of this repository to okay it. So should I go ahead and contact them?

**Comment by angavrilov** [comment]
If they can do it easily, I have nothing against this.

**Comment by dscorbett** [comment]
GitHub’s response:
>Thanks for getting in touch. This request must come directly from angavrilov. They will need to email us.

[Here is the contact page.](https://github.com/contact)

**Comment by JapaMala** [comment]
@angavrilov It's all on you, then.
