### ISSUE TITLE
Prepared meal ingredient field unk10 is the ingredient quality

### ISSUE THREAD

**Issue by milochristiansen** [DFHack/df-structures#158]
What the title says, item_foodst.ingredients[idx].unk_10 is the quality for that ingredient.

**Comment by lethosor** [comment]
Would the `item_quality` enum work here?

**Comment by milochristiansen** [comment]
It should, I never tried to use values higher than 5, but it seems to be like any other quality value so it should work fine...

**Comment by lethosor** [comment]
Done, thanks!

**Comment by milochristiansen** [comment]
Hey! I should be the one saying thanks :P
