### ISSUE TITLE
abstract_building: 64-bit pointer differences

### ISSUE THREAD

**Issue by figment** [DFHack/df-structures#159]
As I test out my 0.43.05 build on Win64 just noting some research and likely unknowns that are pointers rather than integer unknowns based on data alignment.

The following was noted by failure to use the exportlegends script successfully on a world.
Buildings did not have appropriate siteid or position information as well as names so changed the following on abstract_building and now that works:

     df.world-site.xml | 6 +++---
     1 file changed, 3 insertions(+), 3 deletions(-)

    diff --git a/df.world-site.xml b/df.world-site.xml
    index 7ed2360..d234443 100644
    --- a/df.world-site.xml
    +++ b/df.world-site.xml
    @@ -69,9 +69,9 @@
             <int32_t name='unk3'/>
             <stl-vector name='unk4' type-name='int32_t'/>
             <int32_t name='site_owner_id' ref-target='historical_entity'/>
    -        <int32_t name='unk_v42_1' comment='v0.42.01'/>
    -        <int32_t name='unk_v42_2' comment='v0.42.01'/>
    -        <int32_t name='unk_v42_3' comment='v0.42.01'/>
    +        <pointer name='unk_v42_1' comment='v0.42.01'/>
    +        <pointer name='unk_v42_2' comment='v0.42.01'/>
    +        <pointer name='unk_v42_3' comment='v0.42.01'/>
             <int32_t name='site_id' ref-target='world_site'
                      comment='not initialized/saved/loaded, assumed member of base class'/>
             <compound name='pos' type-name='coord2d' comment='v0.42.01'/>

Side-question: Is it possible to load worlds created on 32-bit worlds on the 64-bit equivalent environment?  I suppose I can just try but would help isolate this kind of thing much faster if that worked.

**Comment by lethosor** [comment]
Thanks!

And yes, it's possible to load the same save in both versions. You should use two different copies of the same save, though, and not symlink one data/save folder to the other.

**Comment by figment** [comment]
Thanks.  I'll play try that out to try and play Spot the Difference.

**Comment by lethosor** [comment]
I totally forgot about this, but it should be fixed in https://github.com/DFHack/df-structures/commit/81e2cf023422ad6f01061db12586a0589ef6eac5
