### ISSUE TITLE
Bitfields cannot be used inside unions

### ISSUE THREAD

**Issue by dscorbett** [DFHack/df-structures#169]
Bitfields cannot be used inside unions because they have non-trivial default constructors. This necessitates the use of `int32_t` in a few places a bitfield would be preferable (see 22819e2e37c03505d184fc4e89c4a4fd67b92995). The default constructor, [generated by Bitfield.pm](https://github.com/DFHack/df-structures/blob/274687583728a5e4981d25bab44b4f0c08cd78c5/Bitfield.pm#L80), looks like `foo(int32_t whole_ = 0) : whole(whole_) {};`. This allows constructing a bitfield with some flags set.

I propose that the non-trivial constructor be removed. The compiler-synthesized constructor will set all the flags to 0. The convenience of bitfields in unions outweighs the inconvenience of not having the current constructor, especially for Lua.

A quick check indicates that the one-argument form is not even used (except with 0, which is unnecessary), so this change would not break anything:
```console
$ gawk 'match($0, /<bitfield(-type)? .*name=.(\w*)/, a) { print "\\<" (a[1] ? "" : "T_") a[2] " *\\(\\w\\+ *\\)\\?(" }' df-structures/df.*.xml | grep -f - -r dfhack
dfhack/library/include/modules/MapCache.h:    df::tile_designation DesignationAt(df::coord2d p)
dfhack/library/include/modules/MapCache.h:    df::tile_occupancy OccupancyAt(df::coord2d p)
dfhack/library/include/modules/MapCache.h:    df::tile_designation designationAt (DFCoord tilecoord)
dfhack/library/include/modules/MapCache.h:        return b ? b->DesignationAt(tilecoord) : df::tile_designation(0);
dfhack/library/include/modules/MapCache.h:    df::tile_occupancy occupancyAt (DFCoord tilecoord)
dfhack/library/include/modules/MapCache.h:        return b ? b->OccupancyAt(tilecoord) : df::tile_occupancy(0);
dfhack/library/modules/Gui.cpp:    df::announcement_flags mode(0);
dfhack/library/modules/Gui.cpp:    df::announcement_flags mode(0);
dfhack/library/modules/Gui.cpp:    df::announcement_flags flags(0);
dfhack/library/modules/Maps.cpp:    df::tile_designation dsgn(0);
dfhack/plugins/burrows.cpp:    df::tile_designation mask(0);
dfhack/plugins/burrows.cpp:    df::tile_designation value(0);
dfhack/plugins/workflow.cpp:    df::dfhack_material_category mat_mask(0);
dfhack/plugins/workflow.cpp:    df::dfhack_material_category mat_mask(0);
```

**Comment by warmist** [comment]
Is this still an issue with new msvc? https://msdn.microsoft.com/en-us/library/hh567368.aspx this indicates that it should be okay with it.

**Comment by lethosor** [comment]
And according to https://gcc.gnu.org/projects/cxx-status.html#cxx11 it should work in GCC >= 4.6. There was some discussion of dropping support for 4.5 in favor of some other C++11 features (range-based for, etc.), so if this does work with 4.6, that could be another reason to move away from 4.5.

**Comment by lethosor** [comment]
@warmist I just checked and this does not compile with GCC 4.8:
```cpp
struct A {
    A (int x=0) : x(x) {}
    int x;
};

union U {
    A a;
    int i;
};

U u;
```

`error: union member 'U::a' with non-trivial 'A::A(int)'`

@dscorbett I don't care too much about removing the constructor, since it's possible to do the same thing by just setting `whole_` after constructing the union. I'm not sure if removing it would break something in the Lua API, though. Have you tried compiling with the bitfield constructors removed?

**Comment by dscorbett** [comment]
Once I removed them from a few plugins, compiling without the bitfield constructors completed without an error message. I can make a pull request, but it will be untested: the dfhack script has a “wrong architecture” error, even without this change.

**Comment by lethosor** [comment]
What platform?

**Comment by dscorbett** [comment]
I am using OS X 10.11.5 with gcc 4.8. The error message is:
```
dyld: could not load inserted library './hack/libdfhack.dylib' because no suitable image found.  Did find:
	./hack/libdfhack.dylib: mach-o, but wrong architecture

./dfhack: line 15: 48704 Trace/BPT trap: 5       DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

```
This message from the make log looks relevant:
```
[ 55%] Linking CXX shared library libdfhack.dylib
ld: warning: ignoring file /Users/dcorbett/df/df_osx/libs/libstdc++.6.dylib, file was built for x86_64 which is not the architecture being linked (i386): /Users/dcorbett/df/df_osx/libs/libstdc++.6.dylib
```

**Comment by lethosor** [comment]
Looks like you're building a 32-bit DFHack for 64-bit DF, or possibly the other way around (but I think the first is more likely). Try passing -DDFHACK_BUILD_ARCH=64 to cmake if you haven't.

**Comment by dscorbett** [comment]
That worked. Thanks! I can confirm that with my changes getting and setting a bitfield’s bits in Lua still works, both individually and using a table.

**Comment by lethosor** [comment]
I confirmed that the default constructor zero-initializes the bitfield (and http://stackoverflow.com/questions/321351 agrees). Looks good to me.

**Comment by lethosor** [comment]
Looks like that compiles, and `knowledge_scholar_category_flag` can now be used more sensibly in C++ and Lua. (Note that the flags in unions like that one are not initialized, although flags in structures are reliably initialized now.)
