### ISSUE TITLE
On the organization of df.world_data.xml:world_data.feature_map

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#206]
I believe this structure to be a two dimensional array ceiling (map_width/16) * ceiling (map_height/16). However, these top level elements seem to be allocated only when needed, i.e. the pointers to the cells may be null pointers, leading to DF crashing when trying to access them. Once allocated the cells seem to be retained, however for the rest of the game session.
  The allocation of a cell does not mean the contents is allocated, though, only that the top structure is. The
'features' element is frequently a null pointer which doesn't get allocated until it's needed, i.e. when one of the world tiles in the cell needs to have its feature data defined.
 Once the features structure is allocated it still isn't complete, as the 'feature_init' 16*16 matrix over the world map tiles of the cell only populates the feature lists of the world tiles it needs data for, with the other tiles having zero length lists. Again, once a list has been populated during the current session it remains populated.

If verified, it would be useful to have the structure and its probable state of incompleteness being documented in a legible fashion in the XML file (The explanation of the world_region_details.edges field is a precedence of a larger description in the same file).

**Comment by lethosor** [comment]
This seems reasonable, based on the little I know about how features work - want to add it? Any data is generally better than no data, and I trust your research here (although feel free to verify since it's been a while).

**Comment by PatrikLundell** [comment]
Some of the above is incorrect, according to later experience. It seems feature maps are unloaded dynamically as well. However, once data has been added they reappear when the hacked structure is reloaded, so it actually takes effect (if I remember correctly, adding a river at the end has it shown at the top when the structure is reloaded).
This functionality is used by the Biome Manipulator for river manipulation, as well as Candy Corrector for candy spires that go AWOL in world with less than 3 cavern layers. The data is read by the Embark Assistant. Given this, I think it's reasonably verified.

I think I can produce such a PR.

**Comment by lethosor** [comment]
Looking at this again, I could use some clarification. This is part of the generated C++ in world_data.h:
```cpp
    struct DFHACK_EXPORT T_feature_map {
      int16_t x;
      int16_t y;
      struct DFHACK_EXPORT T_features {
        std::vector<df::feature_init* > feature_init[16][16];
        int32_t unk[16][16][30];
        static struct_identity _identity;
      public:
        T_features();
      };
      T_features* features;
      int16_t* unk_8;
      int32_t* unk_c;
      static struct_identity _identity;
    public:
      T_feature_map();
    };
    T_feature_map** feature_map;
```
feature_map is the field, T_feature_map is the type. As you can see, feature_map is a double pointer (basically a 2D array like you described) of T_feature_map instances. There are already a few map block things in world.map that follow a similar pattern. `feature_map[x][y].features` has a couple static 2D arrays inside it as well (which are easier to access, since you don't have to deal with null pointers).

I think a comment that feature_map pointers are only non-null if they're needed would help, but other than that, I'm not sure if anything needs to be changed. Is there something else I'm missing?

**Comment by PatrikLundell** [comment]
It's purely a matter of adding comments, not changing the structure itself.
