### ISSUE TITLE
perfomance_skills?

### ISSUE THREAD

**Issue by Putnam3145** [DFHack/df-structures#210]
df.unit.status.current_soul.**perfomance**_skills. Is this intentional?

**Comment by quietust** [comment]
No.

**Comment by Putnam3145** [comment]
Ah, appears to have been fixed by https://github.com/DFHack/df-structures/commit/5f4a301d0ad862523778bb7a9043e7f8aa3c8de0, which somehow wasn't showing up in my searches nor in any copies of the game I have. How weird.

**Comment by lethosor** [comment]
Are you saying you still see the old name in-game?

**Comment by Putnam3145** [comment]
No, somehow none of my copies were fully updated and I didn't notice this.
