### ISSUE TITLE
df.interaction.xml: interaction_target.getType returns suspect type interaction_source_type

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#212]
I would expect the return type to be interaction_TARGET_type, which doesn't seem to be exported.
Using the (C++) results as if they were interaction_target_type (checking for REGION rather than CORPSE and DISTURBANCE rather than MATERIAL) seems to give the correct result from a first attempt.

**Comment by quietust** [comment]
Fixed in 8f8d85515c88de397559e4003b60b956ee41fe83.
