### ISSUE TITLE
EnumItem feature_underworld_from_layer should be underworld_from_layer

### ISSUE THREAD

**Issue by ragundo** [DFHack/df-structures#215]
```
enum feature_type : int32_t 
{

        outdoor_river,
        cave,
        pit,
        magma_pool,
        volcano,
        deep_special_tube,
        deep_surface_portal,
        subterranean_from_layer,
        magma_core_from_layer,
        feature_underworld_from_layer
      };
```
The word "feature" in feature_underworld_from_layer is redundant and should be removed, as is in all the others values of this enum.

This complicates the automatic deduction of the subclass name using this enum:
enum name -> class_name
_outdoor_river -> feature_outdoor_river:_ **OK**
_feature_underworld_from_layer -> feature_feature_underworld_from_layer:_ **WRONG**

**Comment by ragundo** [comment]
Thanks for solving the issue, but the commit broke dfhack in the following files:

- https://github.com/DFHack/dfhack/blob/master/plugins/reveal.cpp#L47
- https://github.com/DFHack/dfhack/blob/master/plugins/prospector.cpp#L724
- https://github.com/DFHack/dfhack/blob/master/library/modules/Maps.cpp#L94

just change feature_underworld_from_layer to underworld_from_layer and go

**Comment by quietust** [comment]
Technically, it won't break DFHack _until_ library/xml gets updated - submodules are useful that way.
