### ISSUE TITLE
squad_order_type defines KILL_HF, but no struct squad_order_kill_hf really exits

### ISSUE THREAD

**Issue by ragundo** [DFHack/df-structures#216]
If it's defined in the enum, there should be a class with this name (squad_order_kill_hf), but it doesn't exist.
A empty class should be defined (deriving from squad_order, of course) for completeness.
EDIT:
Same for DRIVE_ARMIES_FROM_SITE

**Comment by lethosor** [comment]
Yeah, there's a `squad_order_kill_hfst` class in symbols.xml, meaning it exists in DF (and has vmethods).

**Comment by ragundo** [comment]
But it doesn't appear in codegen.out.xml

**Comment by ragundo** [comment]
Should I create a PR defining all those empty subclasses?

**Comment by lethosor** [comment]
We don't necessarily know if they exist, although if they have vmethods, their vtable addresses should be listed in symbols.xml.
