### ISSUE TITLE
incident misaligned/invalid

### ISSUE THREAD

**Issue by warmist** [DFHack/df-structures#234]
Looks like incident (e.g. global.world.incidents.all[0]) is wrong.
Seems like victim_caste (and other caste?) should be less bytes

**Comment by lethosor** [comment]
From [sizecheck](https://github.com/mifki/df-sizecheck)
```
<type: incident>
  NOT OK 144 280
```
I think you are right - we're missing almost half of that structure (on osx64, at least).
