### ISSUE TITLE
0.44.07-alpha(dev): world_site mapping issues

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#246]
unk_18c is claimed by gui/gm-editor to have a silly number of element, and thus likely is mismapped.
The same goes for entity_links, cultural_identities, and unk_v42_1

**Comment by lethosor** [comment]
Yeah, world_site is known to have changed.

**Comment by lethosor** [comment]
Fixed in 70b6d92e0aee4d2690fe6010050d2d956f0a8d6d?

**Comment by PatrikLundell** [comment]
Yes, as expected...
