### ISSUE TITLE
dfhack_knowledge_scholar_flag missing metadata (complex enum)

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#250]
I've tried to index the type to get at the string from Lua, but just get nil as a result, including with the (as of this writing) brand new 0.44.09 r1 version.
I've compared the generated headers for this type to the randomly selected abstract_building_flags.h generated with 0.44.07 (probably alpha: the latest version I've generated on my computer) and this file contains an extra section for 
"template<> struct DFHACK_EXPORT enum_traits<abstract_building_flags>..."
which has no correspondence in dfhack_knowledge_scholar_flag.h.

Since I can't see any obvious difference in how the two types are defined in the XML, I suspect there is some additional structure outside of the XML file the enum type is defined in that's responsible for the generation of this (very useful) functionality for enums.

**Comment by lethosor** [comment]
That's related to the warning that you see when running codegen.pl (the generate_headers target):
```
Warning: complex enum: dfhack_knowledge_scholar_flag
```
and is due to lines like this: https://github.com/DFHack/df-structures/blob/3c0bf63674d5430deadaf7befaec42f0ec1e8bc5/df.knowledge.xml#L448
codegen currently has no way to generate metadata for enums with holes in them, sorry.

**Comment by PatrikLundell** [comment]
Thanks for explaining it.

**Comment by lethosor** [comment]
Oh, I didn't see your edits. Making new comments would make sure people get notifications. Anyway, I've wanted to support complex enums, since there a few others using a similar trick (but not as large as this one), so that's supported in dfhack/dfhack#1254 now.
