### ISSUE TITLE
df.item.xml:item_flags2.has_written_content may be something else

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#251]
I tried to use the flag to distinguish items with written contents from those without. However, it turned out quite a few scrolls and books have itemimprovement_pagest or itemimprovement_writingst improvements without having this flag set. The flag isn't correlated with one of these improvement types, as both types have been seen together with both flag values, nor have I've seen any correlation with whether the content references something or not (again, both flag values have been seen with and without contents references).

**Comment by lethosor** [comment]
Should the name be removed, or do you have another solution in mind?

**Comment by PatrikLundell** [comment]
I have no idea what the flag actually is. I'd probably remove the name and add a comment indicating that it might be associated with "books", but it's not set on all of them. Somebody has presumably made the observation that it is set on "books", so that should probably be left as a comment.

**Comment by lethosor** [comment]
"unk_book" it is, then

**Comment by lethosor** [comment]
Fortunately, nothing in DFHack appears to actually use this flag, so it should be pretty painless to change.
