### ISSUE TITLE
df.unit-thoughts.xml:unit_thought_type has an additional value, 240

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#255]
Crawling through a DFFD world showed quite a few cases of this value in df.global.world.history.figures[*].info.personality.anon_1.emotions.thought.

It seems this value corresponds to "seeing a <critter's> dead body", which would match with Toady's division of seeing something die and seeing their body into two separate thoughts.

Edit: This logic reproduces the thoughts, so 240 might be named e.g. "SeeDeadBody"
   [240] = {["caption"] = "after seeing [subthought]'s dead body",
                                          ["subthought"] = {"df.global.world.incidents.all id",
                                                            (function (subthought) 
                                                               return incident_victim (subthought)
                                                             end)}},
I haven't looked at what might be responsible for making some thoughts remembered and some not.

Edit 2: Examining a single dorf's thoughts I suspect df.global.world.history.figures[*].info.personality.anon_1.emotions.flags [5] results in a memory thought when set.
That dorf showed 5 memory thoughts on the thoughts screen, and my "thoughts" script modified for this examination (but not uploaded, as it crashes at the end) likewise finds 5 memories of the types the memories cover.
One might consider naming that flag as e.g. "Memory".

**Comment by lethosor** [comment]
Are you comfortable making a PR for these? I can handle the new unit_thought_type, but I'm not sure what the deal with the flags you're talking about is.

**Comment by PatrikLundell** [comment]
Technically I can muster the energy to fight Github, but I've waited for guidance on HOW to update it as per #239 which nobody has bothered comment on (I don't consider a cross reference to similar structures for adventure mode to be any kind of guidance) . The whole thing is in a sorry state, so updating it without addressing the structure is a bit of a turd polishing exercise.
