### ISSUE TITLE
part_of_speech base-type should be int16_t

### ISSUE THREAD

**Issue by ragundo** [DFHack/df-structures#321]
In libray/include/df/part_of_speech.h

`
      enum part_of_speech : int32_t {
        Noun, // 0, 0x0  //etc
 };
 `   

In codegen.out.xml

`<ld:global-type ld:meta="enum-type" ld:level="0" type-name="part_of_speech" last-value="8">`

And its use in df::language_name

`<ld:field ld:level="1" ld:meta="static-array" name="parts_of_speech" count="7" ld:is-container="true">`

` <ld:item ld:subtype="enum" base-type="int16_t" type-name="part_of_speech" ld:level="2" ld:meta="global" ld:enum-size-forced="true"/>`

In gui/gm-editor
![part_of_speech](https://user-images.githubusercontent.com/9405614/56355423-88f27f00-61d6-11e9-99b1-48ce72ee55b6.png)

I was getting incorrect values because I took int32_t as the base field for the enum, as part_of_speech.h says.

So in df.language.xml
`<enum-type type-name='part_of_speech'>`

should be
`<enum-type type-name='part_of_speech' base-type='int16_t'>`

**Comment by lethosor** [comment]
What matters is which integer type is used most. If part_of_speech is usually an int32_t, it should be based on that.

What exactly do you mean by getting incorrect values? The array here should be int16_ts in all languages, so I don't see how you could read from it incorrectly unless you were doing weird stuff with casting.

**Comment by ragundo** [comment]
I don't get the point of having an enum defined as an int32_t (4 bytes) and used later as one int16_t.

The incorrect values I get is because in one parts_of_speech array that I'm processing I use  int32_t as the base type instead of an int16_t, and adding sizeof(int32_t) for the address of the next array element when it should be sizeof(int16_t). That's why I get wrong values. 

For part_of_speech, is defined as one int32_t and used as int16_t and int32_t

Same for world_population_type,  defined as int32_t and used as int8_t and int16_t

**Comment by lethosor** [comment]
All the occurrences I could find:
```
df.creature-raws.xml:        <enum base-type='int16_t' type-name='part_of_speech'
df.language.xml:            <enum base-type='int16_t' type-name='part_of_speech'/>
df.language.xml:                <enum base-type='int32_t' type-name='part_of_speech'/>
df.viewscreen.xml:            <enum base-type='int32_t' type-name='part_of_speech'/>
```
This is a mix of types. We can't control the types of these, or the fact that they are part_of_speech instances. I don't know how exactly Toady does this in his code, but we can't make part_of_speech inherit from both int16_t and int32_t. Since int32_t is the "default" for our purposes, I'd say that's reasonable.

**Comment by ragundo** [comment]
I need then to consider the size of the enum in every place where is referenced and not the one provided in the enum definition. That complicates the parsing.

**Comment by lethosor** [comment]
Yup, sorry. Not sure why DF does things like this sometimes, but it makes things complicated.
