### ISSUE TITLE
Mapping of df.viewscreen.xml viewscreen_titlest v0.47.01

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#345]
Hoping to save some time for whoever ends up doing the mapping...

I'm stuck on figuring out what the layout should be, but have been able to find that there's a 48 byte hole between "arena_savegames" and "str_slaves" (the strings contain the expected texts with that padding), but the data after "str_site" seems to vary between program starts, with nothing looking like it would be "arena_raw_folder". A speculation is that the folder should go into the new hole, but I don't know anything about arena mode or how to get something into the "arena_raw_folder" for testing.

**Comment by quietust** [comment]
The group of 5 vectors has expanded to 7 - all that needs to be determined is which ones are new.

**Comment by PatrikLundell** [comment]
"arena_savegames" follows immediately after "start_savegames" and just before the 48 byte hole (or two vectors). At least the contents of that vector corresponds to the same vector in a 0.44.12 DF when I compare them, i.e. a blank string for the first one and then one for each save in the save folder with the name of that save.

However, it seems you have things in a considerably better hand than I do.
