### ISSUE TITLE
df.interactions.xml:breath_attack_type enum out of sync

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#357]
I'm fairly sure the "new" value 21 is actually what's described as "OTHER", i.e. number 20. This value is found for cat cleaning, head bumping, sapient petting, and for various creatures (haven't checked those in detail) that ought to root, such as turkey and pig.

I've also been able to find a save with 8, 10, and 11 matching up (FIREBALL enum matches with Adv_name "Hurl fireball" for 11, for example).

Somewhere in between 11 and 21 there is probably an additional value. The reason I put "new" in quotes is that I believe value 21 was present in 0.44.12 (and probably earlier) as well.

I don't think I can track it down, as it appears in df.global.world.nemesis.all [*].unit, when unit isn't nil, and df.global.world.units.all[*], and I don't know how to get units there except through normal game play (and I think nemesis[*].unit just refers to a unit in units.all anyway). None of the values between 11 and 21 are present in the random saves I've looked at.

I guess the arena might be usable, if you knew how to spawn FBs and the like, but I'm completely unfamiliar with it. Hacking this field on an available FB (trailing poison gas) did not change FB description text, so that avenue is closed.

**Comment by quietust** [comment]
The new type is "SHARP_ROCK", immediately following TRAILING_ITEM_FLOW (i.e. just before the end).
