### ISSUE TITLE
[0.47] New thoughts

### ISSUE THREAD

**Issue by cvuchener** [DFHack/df-structures#363]
reported here https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/190

The new thought id is 258 "after acceptance of a petition for a guildhall for [guild name]". Subthought is the historical_entity id for the guild.

**Comment by PatrikLundell** [comment]
The text before the slash is the one buried in the text block, while the one after is the very top one that can contain a bit more info.

259: after the establishment of a guildhall for []/The [] has been recognized.
257: Nothing seen.
256: The agreement to establish a temple for [] was abandoned. Top thought. Incorrect parameters for normal one (guild hall parameter probably wrong for god).
255: The temple petition for [] was ignored. Top thought.
254: The temple petition for [] was rejected. Top thought.
253: after the establishment of a temple for []/The [] has been recognized.
252: after the acceptance of a petition for a temple for []/The [] will be recognized.
251: From afar/I was away
250: after abducting somebody/I abducted [].
249: after receiving a cut of corruptly-obtained funds/I received a cut of corruptly-obtained funds.
248: after embezzling funds/I embezzled funds.
247: after accepting bribes in the exchange for leniency/I accepted bribes in exchange for offering leniency.
246: after a performance in an unknown site/There was a performance in an unknown site. Probably wrong parameters.
245: after a scholarly lecture in an unknown site/There was a scholarly lecture in an unknown site.
244: Top thought: I am unnaturally ageless. Presumably either wrong parameters or a requirement for a curse.
243: Top thought: I prey on the blood of civilized creatures.

The above was gotten by pushing a 258 thought to the top (unk2 and strength set to 100) and then trying other numbers. I also changed to thought type to ALARM to get the text to stand out in red.

**Comment by cvuchener** [comment]
http://www.bay12forums.com/smf/index.php?topic=168411.msg8113757#msg8113757 Thought 262 does happen in game despite its empty message. It appears to be guild related.

**Comment by cvuchener** [comment]
> 266: getting divorced

It is actually 265

Also missing from your list:
 - 260: *missing description* / "The guildhall petition for [entity] was rejected"
 - 261: *missing description* / "The guildhall petition for [entity] was ignored"
 - 262: *missing description* / "The agreement to establish a guildhall for [entity] was abandoned"

**Comment by lethosor** [comment]
Since it wasn't referenced yet, I saw some of these added at https://github.com/Dwarf-Therapist/Dwarf-Therapist/pull/205

**Comment by lethosor** [comment]
I think I got most of these in https://github.com/DFHack/df-structures/commit/f23fe268288e154ff65f38932f6e1dcb0c7d8600. Open to suggestions/further changes, of course. I didn't fill in xml_caption for any of them because I'm not really sure what's appropriate for that attribute.
