### ISSUE TITLE
wound_curse_info appears inexact with regards to transformations

### ISSUE THREAD

**Issue by AtomicChicken** [DFHack/df-structures#364]
The following observation was made using gui/gm-editor in 0.47.03 with DFHack build 200219000 Win64. When a unit transforms into a different creature as a result of a syndrome effect, a unit_wound is created to store the effect details in wound_curse_info. Within this, `were_race` and `were_caste` should of course respectively contain the race and caste IDs pertaining to the transformation. However, I have observed that the race ID is being displayed in `were_caste` instead, with the real caste ID seemingly missing.

**Comment by PatrikLundell** [comment]
I was fortunate enough to have a 0.44.12 save with a caged were, so I could compare this save in both 0.44.12 and 0.47.03, and the unit_wound and wound_curse_info looks identical (apart from timer values, as I had to manually advance time for the were to turn, done separately in the two copies). Thus, the layout changed before 0.44.12 (or was mis-mapped originally).
Originally the were was a male elf, but when converted it's converted into an asexual creature (with a gender of -1). The weresquirrel (in this case) is asexual and has a single caste, according to its raws.
Thus, I'd suggest the were_race and were_caste fields are swapped.

**Comment by AtomicChicken** [comment]
I did consider the possibility of the two fields being swapped, but ruled it out before opening the issue. I have observed `were_race` set to 0 or values which definitely don't correspond to the appropriate caste ID, and such values sometimes differ between units transformed into the the exact same creature. I suggest you see this for yourself using simple modded interactions such as the following, which will allow you to directly apply transformation syndromes to units created in arena mode:

> [INTERACTION:TRANSFORM_INTO_DOG_MALE]
> 	[I_SOURCE:CREATURE_ACTION]
> 	[I_TARGET:A:CREATURE]
> 		[IT_LOCATION:CONTEXT_CREATURE]
> 	[I_EFFECT:ADD_SYNDROME]
> 		[IE_TARGET:A]
> 		[IE_IMMEDIATE]
> 		[IE_ARENA_NAME:Transform into male dog]
> 		[SYNDROME]
> 			[CE_BODY_TRANSFORMATION:START:0]
> 			[CE:CREATURE:DOG:MALE]

> [INTERACTION:TRANSFORM_INTO_DOG_FEMALE]
> 	[I_SOURCE:CREATURE_ACTION]
> 	[I_TARGET:A:CREATURE]
> 		[IT_LOCATION:CONTEXT_CREATURE]
> 	[I_EFFECT:ADD_SYNDROME]
> 		[IE_TARGET:A]
> 		[IE_IMMEDIATE]
> 		[IE_ARENA_NAME:Transform into female dog]
> 		[SYNDROME]
> 			[CE_BODY_TRANSFORMATION:START:0]
> 			[CE:CREATURE:DOG:FEMALE]

**Comment by PatrikLundell** [comment]
I'll have to leave that to someone who's familiar with the arena.

**Comment by lethosor** [comment]
Actually, the `unk_1` field you added in 8e9dc3e4 is padding. I took your save from https://github.com/DFHack/df-structures/issues/370#issuecomment-617793752 and loaded it on linux64 and linux32. `devel/visualize-structure world.units.all.1865.body.wounds.0.curse` gives this on linux64 (starting at time_counter):
```
int32_t time_counter
32360000 

int32_t unk_1
d2d2d2d2  

int32_t were_race
ffffffff 

(padding)
ffffffff  

vector<int32_t> body_appearance
00000000 00000000  00000000 00000000  00000000 00000000  
length: 0

vector<int32_t> bp_appearance
00000000 00000000  00000000 00000000  00000000 00000000  
length: 0
```
and this on linux32:
```

**Comment by lethosor** [comment]
What it looks like with the fix in https://github.com/DFHack/df-structures/commit/3a1e2159a55ea46622b8bcfab35333b3674405fd on linux64 (with the added `timing` sub-struct):
```
<type: wound_curse_info.T_timing> timing
00000000 00000000  00000000 00000000  00000000 00000000  32360000 d2d2d2d2  

int32_t were_race
ffffffff 

int32_t were_caste
ffffffff  

vector<int32_t> body_appearance
00000000 00000000  00000000 00000000  00000000 00000000  
length: 0

vector<int32_t> bp_appearance
00000000 00000000  00000000 00000000  00000000 00000000  
length: 0
```
and on linux32:
```
<type: wound_curse_info.T_timing> timing
00000000 00000000  00000000 32360000  

int32_t were_race
ffffffff 

int32_t were_caste
ffffffff  

vector<int32_t> body_appearance
00000000 00000000  00000000 
length: 0

vector<int32_t> bp_appearance
00000000  00000000 00000000  
length: 0
```

I assume were_race and were_caste are in the same order as before 0.47.

Determining exactly where the struct boundary is isn't an exact science - disassembly could probably help some, but I didn't think it was worthwhile here. I would definitely recommend devel/visualize-structure as another (newer) tool to check out (I've [aliased](https://docs.dfhack.org/en/stable/docs/Core.html?highlight=alias#alias) it to `dvs` locally). I expect it works on Windows, although I haven't tested it there myself. Filling uninitialized memory on Windows could be the bigger challenge, but it might not have been necessary in this case since the location of the two `-1`s on win64 alone would indicate where the padding is.

**Comment by AtomicChicken** [comment]
I checked this out on win64 and can confirm that both were_race and were_caste are now correctly showing the values corresponding to the target creature. I also removed all other traces of the syndrome from a test unit and played around with the transformation wound to confirm that changing either of the two values causes the unit to transform accordingly.
