### ISSUE TITLE
invalid strings in unit.enemy.undead.undead_name

### ISSUE THREAD

**Issue by cvuchener** [DFHack/df-structures#369]
Tested on linux32/linux64 using https://github.com/DFHack/dfhack/commit/e26787604a223c924ed96db79e4438e2a2cf806d and c0edb62eba997b09c19b67133d20713901d94bc9

Maybe a missing int32_t before root_body_part_id. There is a valid string one pointer alignment further. The string offset looks like the offset of a int16_t (probably root_body_part_id).

linux64: expected string at 0x7fffbb416388, at 0x7fffbb416390 0x19bbf58 is the empty string.

    7fffbb416370	 0000000000000001 00000003ffffffff
    7fffbb416380	 0000000100000000 d2d2d2d2d2d20000
    7fffbb416390	 00000000019bbf58 0000000000000001

linux32: expected string at 0xde595fd8, at 0xde595fdc 0xde59601c is a valid (non-empty) string.

    de595fc0	 00000001 00000000 ffffffff 00000003
    de595fd0	 00000000 00000000 d2d20003 de59601c
    de595fe0	 00000000 00000000 00000000 00000025

**Comment by lethosor** [comment]
Confirmed on linux64 by creating an undead corpse in the arena
http://github.com/dfhack/dfhack/commit/ffe73028f9bdadd97f8c910a967fd6e95b4e3fff
https://github.com/dfhack/df-structures/commit/7752b16a6e0dd446507928fb6e1b1f96c2509ddb
