### ISSUE TITLE
Suggestion: "Export" is-union and ref-target elements as attributes, plus add discriminant indications

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#372]
- If the ref-target element on fields would be exported as ref-target elements on the fields of the types (when present), it would be possible for e.g. gui/gm-editor to display what fields reference.

- The suggestion for is-union export is more complex, and depends on whether the value is "hard coded" to be boolean. In the best case it's not, in which case it ought to be possible to replace "true" with the name of the field containing the discriminant when it's known (a discriminant is a field that determines which of the overloaded interpretations of a union is the correct one to use). In that case the same logic as the one for ref-target above could be used, i.e. an attribute on the compound element of the type that names the field that controls the interpretation.
If "is-union" is hard coded to a boolean value, it might still be possible to generate a "discriminant" attribute for the field with a value of "nil" if a "discriminant" attribute hasn't been defined manually.
The usage for that would be to allow tools to automatically select the correct interpretation based on the discriminant when present.

**Comment by cvuchener** [comment]
For unions, knowing the discriminant field would not be enough, you would also need to have a map from discriminant values to union fields. It would be more difficult to express, but I would really like if this information was available.

**Comment by PatrikLundell** [comment]
You're right. For it to work we'd need to use a convention of having exactly one field per variant, i.e. each variant would have a single field that would either be a struct or a simple field, and the variants would have to be defined in discriminant value order. That also assumes the discriminant is a simple number/enum starting at 0.

**Comment by lethosor** [comment]
The first bit is the same as https://github.com/DFHack/dfhack/issues/1436, I think (maybe it does belong here...)

**Comment by PatrikLundell** [comment]
Merged into DFHack/dfhack#1436
