### ISSUE TITLE
artifact_record has misaligned fields

### ISSUE THREAD

**Issue by AtomicChicken** [DFHack/df-structures#373]
Win64 0.47.03 using build 200227002, observed via gui/gm-editor:

in `artifact_record`:

These are correct:
`site`
`structure_local`

These each have their corresponding value displaced to the following field:
`subregion`
`feature_layer`
`holder_hf`

**Comment by quietust** [comment]
Has this been resolved by 7c977f4e0b7c640e9ec2e93b716523b955846309?

**Comment by AtomicChicken** [comment]
Confirming as resolved.
