### ISSUE TITLE
some new enum values

### ISSUE THREAD

**Issue by white-rabbit-dfplex** [DFHack/df-structures#395]
`ui_sidebar_mode` takes on value 55 when in the locations submenu while querying a building. For example, [q]uery -> select bed -> [l]ocation. 

`lever_target_type` takes on value 't' while assigning mechanisms, which is the menu seen after selecting a target.

**Comment by lethosor** [comment]
There's another lever_target_type value, `'l'`, when choosing the mechanism to attach to the lever - I added that one too.
