### ISSUE TITLE
army_controller SentToTributary (t12) identification?

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#396]
Someone named the type = 12 variant in the past, which I interpret that to mean it's used for expelled dorfs, which I so far haven't had the means to investigate (no controlled sites to send anyone to, and the one expelled to nowhere is bugged and won't move).

What I think I see, however, is that legitimate visitors seem to generate a t12 army controller for a brief time before showing up on the embark (1-2 days) at which time the army controller disappears (at least from the army_controller.all vector), but as there's no unit identifiers set in those army controllers it's not that easy to confirm a connection, although there seems to be a connection between the anon_7/anon_8 fields and an appearing visitor's purpose.

It's not impossible, however, that the same variant would be used both for inbound visitors and outbound exiles.

Can anyone shed some light on the past identification?

**Comment by lethosor** [comment]
This was fun to dig through - the name came from me in a611cf45, but was based on a comment introduced by @Putnam3145 in a511ba91 (#319). Obviously not much is known about these variants, so feel free to rename it as you see fit.

**Comment by PatrikLundell** [comment]
Thanks for the archeology.
I just tried to exile a dorf, and I get the same result as @Putnam3145 : a new army_controller of type 12 is generated in a paused game (I can't test sending to a site, as I don't have any sites available). Once leaving the map a site gets selected and an army is generated.
It thus seems it's simply a case of the purpose of the variant being broader than expected.
