### ISSUE TITLE
indentifying architectural elements on temples.

### ISSUE THREAD

**Issue by therahedwig** [DFHack/df-structures#397]
Hey, I have the strongest suspicion that this:

https://github.com/DFHack/df-structures/blob/96a8df43d1c4508800c209701ce39ca972579e3b/df.world-site.xml#L116

uses this:

https://github.com/DFHack/df-structures/blob/96a8df43d1c4508800c209701ce39ca972579e3b/df.history.xml#L1452

Running a script over all the abstract buildings, they don't go beyond 11 in value, this array also only shows up on temples, and the temple I am currently looking at has all the architectural elements it ought to have, but I am not yet 100% sure?

Also, I figured out that abstractbuilding.unk3 and abtractbuilding.unk4 are for the relationship between tombs and catacombs. Catacombs hold a list of their tombs in unk4, and tombs hold which catacomb they're in in unk3, but I am not sure what these should be named? Like, child abstract building ids and parent abstract building?

**Comment by PatrikLundell** [comment]
I'd suggest "parent_building_id" and "child_building_id" with the ref-target specifying that they're abstract buildings.

For verification of the suspicion, I'd want a couple of more checks, i.e. two-three additional temples checked out, and even better if you could use a script to identify a set of temples that together ought to have the whole set of features and investigate those. As I assume you're using an adventurer, I'd understand if that would be a bit much to ask, though.

**Comment by therahedwig** [comment]
Well, I am going around a few towns to make pictures for the wiki and identify a bunch of stuff (and my adventurer's ingame reason for this is to get to a specific library), it seems to stay consistent with all the temples I have found up till now:

![image](https://user-images.githubusercontent.com/1759191/79982483-b091bc80-84a6-11ea-9f99-82ddd907bdd1.png)
The Church of Veiling - paved_outdoor_area, upper_floors, open_structure, lower_floors, water_pool, detailed_surfaces
![image](https://user-images.githubusercontent.com/1759191/79982565-d15a1200-84a6-11ea-8ec2-e1d9a149000f.png)
The Cathedral of Aces - paved_outdoor_area, pillars_on_the_perimeter, square_of_pillars, upper_floors, lower_floors, water_pool
![image](https://user-images.githubusercontent.com/1759191/79982689-023a4700-84a7-11ea-99a2-574ff8aa2dc5.png)
The Peaceful Chapel - paved_outdoor_area, pillars_on_the_perimeter, square_of_pillars, upper_floors, open_structure, lower_floors

![image](https://user-images.githubusercontent.com/1759191/79982780-1f6f1580-84a7-11ea-821c-1fe3aa38c939.png)
The Temple of Courage - paved_outdoor_area, pillars_on_the_perimeter, square_of_pillars, upper_floors, paved_indoor_areas, water_pool, detailed_surfaces

Lower floors in this case really seems to refer to whether there is an inner sanctum. Not sure what square of pillars means.

You don't happen to know how I'd best reference something that is defined in history while I need it in world-site, do you? :D

**Comment by PatrikLundell** [comment]
Dedicated work!

You'd probably need to be more specific with your question, as I can't figure out what you want to do. There is a class function to check if historical events refer to a specific site, I think, so a brute-force search for that would probably give you a (slightly) smaller set. If you then know what type of event you want you can cut it down further, and a year range would help as well.

**Comment by therahedwig** [comment]
No, I mean, the architecture enum I want to reference in the abstract building (world-site.xml) is currently defined in history.xml. Like, do we need to move it to global or something?

**Comment by PatrikLundell** [comment]
There are types defined all over the place referenced from other XML files, and there are lots of forward references as well, so I think it should just work. I'd try and generate the code to see if it works. It results in a bazillion .h files, one for each enum, and I assume the code generation is able to get the imports right.

**Comment by lethosor** [comment]
Yeah, all types are effectively global (well, in the `df` namespace, and code generation handles including the required headers in other headers), so you can refer to them from other types, regardless of which XML file they're defined in. The only reason there are multiple df.*.xml files is because shoving everything into a single file would be hard to deal with (around 46k lines currently).

**Comment by therahedwig** [comment]
ok, this can be closed, right :)
