### ISSUE TITLE
job.hist_figure_id is "race" for clothing

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#408]
but it may well be overloaded and actually refer to a hist fig for other kinds of jobs: I have no idea about the process by which the field name was assigned originally.

My conclusion is based on using gui/gm-editor on clothing jobs and changing the size specification to see that the field contains the race number for dwarf, elf, human (and -1 of no size specification is made).

**Comment by lethosor** [comment]
It's been hist_figure_id for a long time: https://github.com/DFHack/df-structures/commit/7b89e595811ed81b012a805131aa10a89d451e76
I suspect it was overloaded as a race ID for some newer jobs, so I made it a union in ebce30e. I haven't tried to track down other types of jobs where it's a hist figure ID, though - maybe engraving a slab would be one?
