### ISSUE TITLE
Notes on viewscreen_layer_unit_actionst

### ISSUE THREAD

**Issue by Atkana** [DFHack/df-structures#415]
- `anon_1` might be where reaction categories are stored, based on how the already mapped reactions entry works. Basically, the reactions entry is an indexed table the length of the number of options available in the "create" list of the menu. Each of the entries links to the reaction associated with the option at that position in the create list, however since reaction categories also appear in the create list, and aren't reactions, the entries at their position in the table are nil, rather than linking to a reaction. Since the information for what on the create list is actually a reaction category (rather than a reaction) has to be stored somewhere, and `anon_1` happens to grow and shrink in size to match the number of options in the create list, it makes sense that that information is probably stored there (possibly following a similar format to reactions, but with options for reactions being nil).
- `anon_8` might be options for natural abilities. As a creature with 3 natural abilities, it's the only option with a length of 3. With 2 abilities, it's length of 2.
- `anon_15` might be related to the compose option. A unit that knows 1 form of poem has that at length 1. A unit that knows no forms has length 0.
- `anon_11`, `anon_12`, and `anon_13` are in some way related to acquired powers. While they were previously all length 0, after learning a necromancer secret with 2 powers, `anon_11` became 2 length, while `anon_12` and `anon_13` became 1 length.

**Comment by lethosor** [comment]
Not super familiar with this screen - is it an adventure mode screen?

**Comment by Atkana** [comment]
> Not super familiar with this screen - is it an adventure mode screen?

In the context of the game, it's the action menu in adventure mode that's opened with `x`, where adventure mode reactions are performed, butchery, natural abilities and acquired powers are used, composition, and writing are done.

**Comment by quietust** [comment]
This screen no longer exists as of version 50.xx.
