### ISSUE TITLE
[0.47.05] New thoughts

### ISSUE THREAD

**Issue by cvuchener** [DFHack/df-structures#419]
271: having an intellectual discussion with a friend / I had an intellectual discussion with my friend.
272: sharing a personal insight with a friend / I shared a personal insight with my friend.
273: sharing a friend's personal insight / My friend shared a personal insight with me.
274: discussing her problems with a friend / I discussed my problems with my friend.
275: discussing a friend's problems / My friend discussed their problems with me.

**Comment by cvuchener** [comment]
"friend" actually depends on the subthought which is a `unit_relationship_type` (it can be "spouse", "mother", "father", "lover", "sibling", "child", "friend", "acquaintance", other values use "somebody").

**Comment by lethosor** [comment]
Good to know - these do indeed appear to be new in 0.47.05
