### ISSUE TITLE
unit_personality alignment changes in 0.47.05

### ISSUE THREAD

**Issue by lethosor** [DFHack/df-structures#420]
Originally posted by @cvuchener in https://github.com/DFHack/df-structures/issues/418#issuecomment-770221376

> I think there is a new int32_t (or smaller) somewhere before `unit_personality.needs`.

> `unit_personality.combat_hardened` did not move, so the new field is between them (from testing with linux32/linux64).

**Comment by lethosor** [comment]
@cvuchener I can't seem to reproduce this on 0.47.05 linux64 - all values of unit_personality for one dwarf (including undistracted_focus at the end) match what they are in 0.47.04

**Comment by cvuchener** [comment]
No issue with linux64, the new field is hidden in padding. It is only visible with 32 bits builds, the `needs` vector has an absurd size.

**Comment by lethosor** [comment]
Ah, makes sense. I haven't set up 32-bit 0.47.05 yet.

Confirmed that there are 4 bytes of padding initialized to 0 for the dwarf above that is uninitialized for the same dwarf in 0.47.04 (between combat_hardened and needs, like you said). I'll add that.
