### ISSUE TITLE
viewscreen_itemst.unk_34 not identified

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/df-structures#44]
https://github.com/DFHack/scripts/blob/master/view-item-info.lua#L388

I don't know any more than that, since I just modified the script `NB_item_info`.

**Comment by quietust** [comment]
Some research and experimenting has confirmed that it's actually a list of **spatter** pointers (exactly the same ones that were stored with the item), so the field is being renamed to "entry_spatters" with PR #320.
