### ISSUE TITLE
Adventure mode tile flags

### ISSUE THREAD

**Issue by Bumber64** [DFHack/df-structures#448]
According to Toady in a recent FotF, adventure mode uses some of the tile flags differently than dwarf mode. For instance, tile designation 0x10 indicates that the tile is currently visible to the adventurer, rather than the first bit of a dig designation.

More research needs to be done, and ~~a union created for the flags~~. Union not possible on bitfields? Use comments?

**Comment by Bumber64** [comment]
Response from Toady:
```
Yeah, 4 through 9.  4 is 'lit', 5 is 'visible', 6-8 are that green memory map thing, and 9 is 'original cave', which impacts what name is displayed at the bottom maybe, maybe some placement stuff too though I don't recall.

In dwarf mode, 5-9 are used for designations (digging and smoothing.)  4 is for stockpiles.
```

Numbers are Nth bit.

**Comment by Bumber64** [comment]
From testing:
``0x8 lit`` not hidden by darkness and 0x10 is true (if controlling a unit that can see in dark, this should be same as 0x10 for all tiles.)
``0x10 visible`` in line of sight
``0x20 furniture_memory`` true even if tile is currently visible, displays cyan icon when in fog of war
``0x40 item_memory`` displays green
``0x80 creature_memory`` displays purple
``0x100 original_cave`` display lair name in UI when standing here

**Comment by lethosor** [comment]
> More research needs to be done, and ~a union created for the flags~. Union not possible on bitfields? Use comments?

What I meant in https://github.com/DFHack/dfhack/pull/2113#discussion_r883280600 was that a union _inside_ a bitfield is not possible. A union _of_ bitfields is, as far as I know, and might end up making more sense anyway if multiple fields are different.
