### ISSUE TITLE
New global - the type of building being linked to a lever/pressure plate

### ISSUE THREAD

**Issue by pronvit** [DFHack/df-structures#45]
I seem to have found a new global, it's a one byte value immediately following `ui_workshop_in_add` and specifies the type of building being linked to a lever/pressure plate. Interesting thing is that it takes not values from `building_type`, but character code of a key you use to initiate linkage, e.g. `b` for bridge, ... , `T` for track stop. It's set to `0xff` when not in the linkage mode.

EDIT: Also it's set to `t` when choosing a mechanism for the target, and to `l` when choosing a mechanism for the lever/pressure plate (with `ui_building_assign_items` holding the list of choices).

Since globals need to be updated manually for new DF versions, what's the procedure of adding a new one?

**Comment by lethosor** [comment]
This seems like it should be fairly easy to locate with find-offsets, once a scan is implemented for it.
(@quietust says he identified this in 0.23, by the way, so it could use character codes because of its age.)

**Comment by lethosor** [comment]
I've gotten a scan for this in find-offsets to mostly work.
