### ISSUE TITLE
List of structures-related issues on main DFHack repo

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/df-structures#46]
* DFHack/DFHack#599 Profession lists and skill tokens
* DFHack/DFHack#571 world.cultural_identity
* DFHack/DFHack#551 viewscreen_choose_start_sitest misaligned
* DFHack/DFHack#529 world.unk_90 research

**Comment by lethosor** [comment]
597 isn't structure-related

**Comment by lethosor** [comment]
I migrated the ones that I reported. @scamtank, could you move yours?

**Comment by PeridexisErrant** [comment]
All issues migrated.
