### ISSUE TITLE
Irritation level

### ISSUE THREAD

**Issue by Bumber64** [DFHack/df-structures#460]
From Toady:
``Yeah, there's an irritation level for every underground feature.  That's been true for a long time, but it was only used by forgotten beasts and there other bits there that made it not matter very much.  Now it matters more tightly for forgotten beasts and also underground animal people.  And there's an aboveground version.``

``Irritation is measure for each layer of the fort separately, and I don't think there's more than one civ per layer locally, though I don't recall precisely how they divide space up.``

There's an irritation level for for every underground feature, which is checked for forgotten beast attacks.

**Comment by quietust** [comment]
Based on my analysis of version 0.28.181.40d, `feature.unk_1` should be the irritation level (maxes out at 10000) and `feature.unk_2` should be the total number of attacks instigated in response to said irritation (maxes out at 10).

To my knowledge, the only action which actually results in irritation is completing a "Dump Item" job within the feature itself, and the amount of irritation is proportional to the weight of the item - historically, this was to handle dumping garbage into the chasm.

**Comment by quietust** [comment]
Closed with #468
