### ISSUE TITLE
structure update placeholder

### ISSUE THREAD

**Issue by ab9rf** [DFHack/df-structures#479]
I have a small but growing batch of structure discoveries that I'm collecting. Rather than dribble them in one at a time, I'm batching them up and will commit them when we're close to release.

Thus, this issue serves as a placeholder to act as a blocker until I have enough of these to justify a push, or we get close to release

**Comment by myk002** [comment]
I'm thinking of spinning the final 0.47.05 DFHack release in 2 to 3 weeks. Will you be able to get this in before then?

**Comment by ab9rf** [comment]
i'll send through whatever is ready at whatever deadline you want to set

**Comment by myk002** [comment]
Let's shoot for Dec 6ish since you might be busy with other things after that date

**Comment by ab9rf** [comment]
tbh i'm an election junkie so yes i'm going to be busy on november 6, but not with dwarf fortress

i'll aim for december 2, that'll give time for review before we hit freeze
