### ISSUE TITLE
Misalignment Tool Findings

### ISSUE THREAD

**Issue by 20k** [DFHack/df-structures#538]
- [x] caste_raw: expected 17144, real: 17160
- [x] plant_growth: expected 328, real 344
- [x] army_controller: expected 200, got 224
- [x] creature_raw: expected 9544, got 9552
- [x] building_furnacest.design: expected 48, got 32
- [x] building_weaponrackst: expected 360, got 336
- [x] unit_complaint: expected 12, got 8
- [x] entity_position: expected 904, got 944
- [ ] historical_figure_info.T_personality.personality: expected 2656, got 2664 edit: possibly, let me check 
- [ ] descriptor_shape: expected 208, got 288? Does this have any derived types?
- [ ] descriptor_color: expected 128, got 184
- [ ] poetic_form_subject_target: expected 4, got 12
- [ ] Our description for squad_schedule_entry is probably wrong (which also bears out my experience with it): expected 88, got 1056 ie its allocated as a big ol slab
- [ ] historical_figure_info: masterpieces: expected 96, got 504
- [ ] historical_figure_relationships.T_intrigues.T_unk12.T_unk_data.ptr_1: expected 12, got 16
- [ ] rhythm_pattern.T_bars -> beat: expected 4, got 8
- [ ] Unsure how unions work or if they're managed so: agreement_details::T_data.Citizenship: Expected 12, got 20. agreement_details::T_data.Residency expected 16, got 24. agreement_details.T_data.Parley expected 8, got 24. agreement_details.T_data.Location: expected 32, got 36

Possibly just invalid
- [X] army_controller.mission_report: expected 120, got 4 (?)
- [X] army_controller.mission_report -> campaigns is invalid. Might just be a bad army controller

Possibly just invalid:
- [ ] world.buildings.other.ARMOR_STAND.1.relations.2.assigned_unit.status.current_soul.personality <type: unit_personality> -> memories expected 600 got 728
- [ ] world.buildings.other.ARMOR_STAND.1.relations.2.assigned_unit.status.current_soul.personality.memories <type: unit_personality.T_memories> -> core_memories

- [ ] likely barracks, entry in world.buildings.other.ANY_BARRACKS: expected 360, got 336

**Comment by 20k** [comment]
Different save: 
- [ ] historical_figure_relationships.T_intrigues.T_unk12.T_unk_data -> ptr_0 expected 16 got 12
- [ ] agreement_details.T_data -> PlotAbduct expected 12 got 16 (see: union disclaimer)
- [ ] <type: abstract_building_libraryst> -> scribeinfo expected 48 got 40
- [ ] world.buildings.other.ANY_STORAGE vector<building*> -> 121 expected 360 got 336 (probably not the same thing as barracks. Has building* shrunk?)

**Comment by 20k** [comment]
Per request: all misaligned designs so far
- [] type: building_water_wheelst -> design expected 48 got 32
- [] type: building_bridgest -> design expected 48 got 32
- [] type: building_wellst -> design expected 48 got 32
- [] type: building_screw_pumpst -> design expected 48 got 32
- [] type: building_wellst -> design expected 48 got 32
- [] type: building_tradedepotst -> design expected 48 got 32
- [] type: building_archerytargetst -> design expected 48 got 32

**Comment by 20k** [comment]
unk_5 probably doesn't contain histfigs. This then OOM'd

- [ ] world.history.unk_5 vector<historical_figure*> -> 38 expected 376 got 1024
- [ ] world.history.unk_5.53 <type: historical_figure> -> entity_links

**Comment by 20k** [comment]
INVALID POINTER ALLOCATION SIZE (windows heap debugging)
world.army_controllers.all.739.data <type: army_controller.T_data> -> InvasionOrder expected 104 got 128

This is with updated XMLs

**Comment by quietust** [comment]
How many of the old errors mentioned above are still present?

**Comment by 20k** [comment]
I haven't taken the latest army controller xml change yet, these are still showing up as invalid:

<type: agreement_details_data_citizenship>
<type: army_controller_invasion_order>
<type: historical_figure_relationships.T_intrigues.T_unk12.T_unk_data.T_ptr_1>
<type: beat>
<type: agreement_details_data_parley>
<type: descriptor_color>
<type: descriptor_shape>
<type: agreement_details_data_residency>
<type: historical_figure_info.T_masterpieces>
<type: unit_personality.T_memories>
<type: agreement_details_data_location>

<type: agreement_details_data_plot_abduct>
<type: location_scribe_jobs>
<type: agreement_details_data_location>
<type: historical_figure_relationships.T_intrigues.T_unk12.T_unk_data.T_ptr_0>

**Comment by quietust** [comment]
`army_controller_invasion_order` is one of the ones I fixed - I'll take a look at the others shortly.

**Comment by myk002** [comment]
Latest list of bad types: 

- <type: historical_figure_relationships.T_intrigues.T_unk12.T_unk_data.T_ptr_1> (expected 12 got 16)
- <type: unit_personality.T_memories> (expected 600 got 728)
- <type: beat> (expected 4 got 8)
- <type: historical_figure_info.T_masterpieces> (expected 96 got 504)

**Comment by quietust** [comment]
Commit ee0c038bca5f46974a2040778823083b641b6265 on my fork should fix everything but `beat` for now - `intrigues.unk_12.unk_data` is a union, so the size of `ptr_1` was wrong because that one was actually a `ptr_0`.
