### ISSUE TITLE
Anons in viewscreen_choose_start_sitest

### ISSUE THREAD

**Issue by ElsaTheHobo** [DFHack/df-structures#546]
I found out what some of the variables in viewscreen viewscreen_choose_start_sitest are for

anon_1/anon_2: appears to be the x and y position of the "embark square" in region tiles
anon_5/anon_6: correlates to the x and y position of the top left corner of the "embark square" where you choose a location. units are in embark tiles
anon_7/anon_8: x and y pos of the bottom right corner of the embark square.

anon_9: setting it to 1 immediately made me embark without options and started the tutorial. gameplay was very buggy before i quit out (try setting anon_9 to 1, then opening and closing the world map screen)

anon_10: setting it to 1 showed the "play now / prepare carefully" screen , as if i had chosen a site

anon_11: not sure, stays at 0 when i try to change it

anon_16/anon_17: x and y pos for which region tile the mouse is hovering over. it updates whenever the mouse is moved, and changing the values manually does not change any info in the site finder. in a small world top left is 0,0 and bottom right is 64,64

anon_19 - anon_22 : the index for each vector appears to correlate to an entity id, 0 = MOUNTAINS, 1 = PLAINS, etc. if the closest civ for that entity can't access where the player's mouse is hovering, either because of distance or because the mouse is over an ocean, then the value will be a default value or nil. dwarf entity (id 0) is also set to default values, probably because your civ doesn't show up in the site finder

anon_21: looks like the mouse's distance in region tiles from an entity in the site finder. -1 = farther than 30 units away. editing these values shows up in the site finder, 1 = "here", 10 = 1 day, 100 = 11 days, 1000 = 111 days. 2000 = 222 days, etc.

anon_22: the civ's hostility, shown in the site finder. 0 = war, 1 and 2 = hostile, 3 = no trade, 4 = default

anon_23: 0 = zoomed out, 1 = zoomed in

anon_24/anon_25: the camera's x and y position for which embark tile the camera is centered on while zoomed in. updates whenever you drag the camera around, does not update while zoomed out. in a small world top left is 0,0 bottom right is 1039,1039

anon_34: whether or not your embarking (have the blue embark square), 0 = not embarking, 1 = embarking

anon_35/anon_36: top left of embark square's x and y position while at confirmation
anon_37/anon_38: bottom right corner of embark square ^
manually changing anon_35 - _38 lets you resize your embark. i made a 1 x 20 embark this way

**Comment by quietust** [comment]
We actually were given access to a "Toady header" which contained the layouts of _all_ of the viewscreens, but for whatever reason I never applied those names for `choose_start_site` - I've applied most of them with 632a5930ed40616d62043de1234bf007dbbbc634.
