### ISSUE TITLE
New vermin_category value 8 might be "Roaming"

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#565]
vermin_category (in df.vermin.xml) has been detected to use a new enum value of 8, and I believe it means "Roaming" and to be associated with vermin_flags.is_roaming_colony being true.

However, my evidence is a bit on the thin side:

In a newly created embark vermin showed up after having been left to run for a short time (probably less than a minute). 3 vermin had a vermin_category value of 8. Two of these were bumblebees and the third was a honey bee, and all 3 also were the only vermin to have the vermin_flags.is_roaming_colony set. At the same time, there were at least one honey bee and at least one bumblebee that instead had the vermin_category value of Searched (and, obviously, the vermin_flags.is_roaming_colony set to false).

**Comment by quietust** [comment]
Added as "FromColony"
