### ISSUE TITLE
markup_text_boxst.unk_v50_2 vector contains entries similar to general_ref

### ISSUE THREAD

**Issue by Bumber64** [DFHack/df-structures#569]
Some code I've reverse engineered starting at `loc_14096F9A2` in v50.05:
```
int32_t unk_0 = -1;

if (string_D90 == "HF") //HISTORICAL_FIGURE
    unk_0 = 0;
if (string_D90 == "SITE")
    unk_0 = 1;
if (string_D90 == "ARTIFACT")
    unk_0 = 2;
if (string_D90 == "BOOK")
    unk_0 = 3;
if (string_D90 == "SR") //SUBREGION?
    unk_0 = 4;
if (string_D90 == "FL") //FEATURE_LAYER?
    unk_0 = 5;
if (string_D90 == "ENT") //ENTITY
    unk_0 = 6;
if (string_D90 == "AB") //ABSTRACT_BUILDING?
    unk_0 = 7;
if (string_D90 == "EPOP") //ENTITY_POP
    unk_0 = 8;
if (string_D90 == "ART_IMAGE")
    unk_0 = 9;
if (string_D90 == "ERA")
    unk_0 = 10;
if (string_D90 == "HEC")
    unk_0 = 11;

int32_t unk_4 = atoi(string_DB0);
int32_t unk_8 = -1;

if (unk_0 == 7 || unk_0 == 9)
{
    //some parsing
    unk_8 = atoi(string_D50);
}

if (unk_0 != -1)
{
    df::ref_thing *ptr = new df::ref_thing();
    ptr->unk_0 = unk_0;
    ptr->unk_4 = unk_4;
    ptr->unk_8 = unk_8;

    *world.status.unk_v50_1.unk_v50_2.push_back(ptr);
}
```
It looks similar to a `general_ref`. IDK if we're just misaligned, or it's a separate struct.

**Comment by ab9rf** [comment]
for reference, the corresponding location in v50.07-steam is `1409af072`; the function begins at `14096e700`

**Comment by Bumber64** [comment]
It ("ref_thing") looked like a `general_ref` in that the tokens here that define `unk_0` are similar to the enum values of `general_ref_type`. Structurally it's closer to `specific_ref`, _however_ `unk_4` and `unk_8` are ids instead pointers.

It's since been determined that this struct is likely used by hyperlinks in the `markup_text_box`. (See the issue that mentions this one.) I guess I'll close this issue and use the other one for research instead.

**Comment by ab9rf** [comment]
i'm reopening this because we can get ground truth on this from the bay12 header dump and so we might as well do so

**Comment by Bumber64** [comment]
Looks like there won't be any need for that. I just confirmed that these are refs to legends pages by messing around with the `text_box`es found in the entries in `gview.view.child.page` via the gm-editor in legends mode. Changing `unk_0` changes the text color and the page it links to (provided `unk_4` is still a valid ref, otherwise clicking does nothing.)

The enum is similar to `legend_pagest.T_mode`, but doesn't quite line up, so we need to create a separate one like:
```
<enum-type type-name='legends_page_ref_type'>
    <enum-item name='NONE' value='-1'/>
    <enum-item name='HF'/>
    <enum-item name='SITE'/>
    <enum-item name='ARTIFACT'/>
    <enum-item name='BOOK'/>
    <enum-item name='SR'/>
    <enum-item name='FL'/>
    <enum-item name='ENT'/>
    <enum-item name='AB'/>
    <enum-item name='EPOP'/>
    <enum-item name='ART_IMAGE'/>
    <enum-item name='ERA'/>
    <enum-item name='HEC'/>
</enum-type>
```

**Comment by ab9rf** [comment]
i've found that enum in bay12 headers (it's `MarkupTextLinkType`)

and the structure is called `markup_text_linkst`
