### ISSUE TITLE
item_flags2 bit 3 (unk_book) and building_flags bit 7 seem to identify items/buildings tied to 'Locations'

### ISSUE THREAD

**Issue by Cubittus** [DFHack/df-structures#576]
## `item_flags2` bit 3
(This was last looked at in issue #251)

I noticed a cave spider thread with this `unk_book` flag set and thought it odd. It was in a coffer in my hospital.
I checked other threads in stockpiles and the bit was clear.

I found these other items have the flag set (via `gm-editor`):
- Instruments and goblets in chests in taverns
- Instruments in chests in temples
- plaster, thread and cloth in chests in hospital
- books in bookshelves and on tables (!) in libararies
- scrolls in chests in libraries

These items do not have the flag set:
- clothing owned by a dwarf stored in a cabinet in their bedroom
- books held by dwarfs in the library
- meals on tables in the library
- meals in barrels in a stockpile in the tavern
- items on pedestals in temples
- chests built in temples/taverns/hospitals

It seems to be set when an item is allocaed to and stored for use in a zone that is part of a named *Location*.

I suspect one use of this flag is to hide items from the Move to Depot screen.

## `building_flags` bit 7
(Also mentioned in #532)

This led me to look at chests that are built in *Locations* and I noticed they all had bit 7 set in the building_flags.

Further investigation shows these buildings have the flag set:
- chests, beds, tables and traction benches in hospitals
- thrones, tables and chests in taverns
- chests, some pedestals and altars in temples
- thrones, tables, chests and bookcases in libraries
- pedestals in guild halls

These buildings do not:
- one pedestal and one chest in a temple (Unexpected. This temple had been removed and recreated a couple of times - so maybe a bug?)
- beds, chests, cabinets, armor stands, weapon racks in bedrooms, offices, and dining rooms that do not belong to *Locations*

## Summary

Both these bits seem to correlated with an item or building that belongs to a named *Location*.
I propose these bits are both named `in_location`

**Comment by quietust** [comment]
`item_flags2` bit 3 is now "location_reserved"
`building_flags` bit 7 is now "did_location_value"

Both names come directly from Toady
