### ISSUE TITLE
`plant_raw` flags bit 14 is set whenever a plant has stockpilable growths

### ISSUE THREAD

**Issue by Cubittus** [DFHack/df-structures#592]
Every plant with `plant.flags[14]` set also has `#plant.stockpile_growths > 0` and vice-versa.
This includes all plants with leaves/fruit growths, and a few tree seeds (almonds/acorns/candlenuts/hazelnuts etc)

**Comment by quietust** [comment]
Flag now known as `EDIBLE_GROWTH`
