### ISSUE TITLE
`plotinfo.dipscripts` and `plotinfo.parties`

### ISSUE THREAD

**Issue by ab9rf** [DFHack/df-structures#632]
@lethosor reports that, in 50.09, these two members do not contain objects of the types expected
my research shows that `dipscript` now contains a vector of pointers to objects of the form `struct { std::string, std::vector<std::string> }`; i haven't looked at `parties` yet

@quietust and i concur that `dipscript_info` is probably still used somewhere else (indeed, possibly in `parties`) so instead of changing `dipscript_info` we should probably retype `plotinfo::dipscript` 

code reference: 50.09-steam `FUN_14079aa10`; see also [related discussion on discord](https://discord.com/channels/793331351645323264/873659717174587403/1137349825445240842)

**Comment by quietust** [comment]
This was fixed in commit f2497072e0450d3d1e474b78f63b3602da67bb45
