### ISSUE TITLE
future info: unit flags4

### ISSUE THREAD

**Issue by ab9rf** [DFHack/df-structures#647]
per putnam `unit.flags4 & 8192` will be added in a future release to handle the case of a unit whose last pathfinding attempt failed, indicating that it should attempt to climb or jump at its next opportunity

for version-tracking purposes, related code in 50.09 (steam) may be at `0x140a323c0`  and/or `0x14107ff40`; these 50.09 functions should be version-tracked into 50.10 if possible to investigate changes in behavior in these functions when 50.10 is released

**Comment by quietust** [comment]
Added a "path_failed_recently", along with "portrait_must_be_refreshed" for 16384
