### ISSUE TITLE
`job.item_category` needs to be renamed and retyped

### ISSUE THREAD

**Issue by ab9rf** [DFHack/df-structures#668]
this field is both mistyped and misnamed; it's not a `stockpile_group_set`  and is called `specflag` in toady code

the field encodes multiple overlapping bits depending on job type:

* bit0: `ConstructBuildingSwitchedSpot`, `CleanPatientTriedSoap`, `CleanSelfTriedSoap`, `PlaceTrackVehicleClearedJobs`, `GatherFromZone`, `DrinkItemLookedForNearbyGoblet`, `InterrogationDidOfficeAttempt`
* bit1: `GatherPickTrees`
* bit2: `GatherPickShrubs`
* bit3: `GatherGatherFallen`
* bit4: `GatherNoLadderSearch`
* bit5: `GatherLadderRestricted`
* bit6: `GatherLadderGround`

however there are multiple references in code to this field so renaming it requires coordination

**Comment by quietust** [comment]
Fixed with b20766dd4c1bbd1542418890a22a87089b1bdbac + ee001f264bf7436a6e0a67398173749a5b76d92e + 0489c1224c34cecad88b4b5bc3de1e1f92aa318b
