### ISSUE TITLE
No value for start_dwarf_count in symbols.xml

### ISSUE THREAD

**Issue by benhighley** [DFHack/df-structures#79]
The startdwarf plugin doesn't work because of this.

**Comment by lethosor** [comment]
@jjyg's script to locate it isn't working reliably, possibly due to a DF change.

**Comment by lethosor** [comment]
Fixed in #91 for 0.42.06, although I'd like to keep this open as a reminder until we can fix scan_startdwarfcount or come up with a better method.

**Comment by jjyg** [comment]
The script works by extracting the size of the 'unit' structure from df-structures/symbols.xml so you need an up-to-date description in there for it to work.

It looks like a stl-string was added in unit in 42.06:
 <sv-esk> found unit with "jutting-chin" text in it in adventure mode
 <sv-esk> it seems to be that new 42.06 feature "Used adjectives from physical descriptions for use in adv mode creature designations"

I'll let you guys add that to df-structures.

I also pushed an updated the script to work on recent OSX versions, where the DF code is slightly larger than it was and so mislead the script.

**Comment by sv-esk** [comment]
Sorry, shouldn't add reference in commit. Actual reference is in PR.
